name: Build Status

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Data::Record
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      id: tests
      uses: Kaiepi/raku-container-action@main
